/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kp.cbs;

import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.GridLayout;
import java.util.Objects;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import kp.cbs.creature.Creature;
import kp.cbs.creature.race.Race;
import kp.cbs.creature.race.RacePool;
import kp.cbs.utils.RNG;
import kp.cbs.utils.Utils;

/**
 *
 * @author Asus
 */
public class MainGameInterface extends JFrame
{
    private final PlayerGame game;
    
    public MainGameInterface(PlayerGame game)
    {
        this.game = Objects.requireNonNull(game);
        initComponents();
        init();
    }
    
    public static final void start()
    {
        initialMenu();
    }
    
    private void init()
    {
        setResizable(false);
        Utils.focus(this);
    }
    
    private static void initialMenu()
    {
        EventQueue.invokeLater(() -> {
            final var frame = new JFrame("CBS - Inicio");
            var bnew = new JButton("Partida Nueva");
            var bload = new JButton("Cargar Partida");
            var bquit = new JButton("Salir");
            
            var saves = PlayerGame.getAllSavedNames();

            bnew.addActionListener(e -> newGame(frame));
            bload.addActionListener(e -> loadGame(frame));
            bload.setEnabled(saves.length > 0);
            bquit.addActionListener(e -> { frame.dispose(); System.exit(0); });

            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setPreferredSize(new Dimension(300, 200));
            frame.setLayout(new GridLayout(3, 1));
            frame.add(bnew);
            frame.add(bload);
            frame.add(bquit);
            frame.setResizable(false);
            frame.pack();
            Utils.focus(frame);

            frame.setVisible(true);
        });
    }
    
    private static void openMain(final PlayerGame game)
    {
        EventQueue.invokeLater(() -> {
            new MainGameInterface(game).setVisible(true);
        });
    }
    
    private static void newGame(JFrame frame)
    {
        final var races = RacePool.getInitialRaces();
        if(races.length < 1)
            return;
        var obj = JOptionPane.showInputDialog(frame, "Debes seleccionar la raza de tu criatura inicial", "Escoger Raza",
                JOptionPane.QUESTION_MESSAGE, null, races, races[0]);
        if(obj == null)
            return;
        
        var creature = Creature.createWild((Race) obj, 5, new RNG());
        
        var game = new PlayerGame();
        game.addCreature(creature);
        
        frame.dispose();
        openMain(game);
    }
    
    private static void loadGame(JFrame frame)
    {
        var saves = PlayerGame.getAllSavedNames();
        if(saves.length < 1)
            return;
        
        var obj = JOptionPane.showInputDialog(frame, "¿Que partida quieres cargar?", "Cargar partida",
                JOptionPane.QUESTION_MESSAGE, null, saves, saves[0]);
        if(obj == null || !(obj instanceof String))
            return;
        
        var game = PlayerGame.load((String) obj);
        if(game == null)
            return;
        
        frame.dispose();
        openMain(game);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
