/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kp.cbs.battle;

import java.awt.Color;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Window;
import java.util.Objects;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import kp.cbs.creature.Creature;
import kp.cbs.creature.attack.Attack;
import kp.cbs.creature.attack.AttackModel;
import kp.cbs.creature.attack.AttackPool;
import kp.cbs.creature.attack.AttackSlot;
import kp.cbs.creature.attack.AttackViewer;
import kp.cbs.utils.Utils;

/**
 *
 * @author mpasc
 */
public class LearnAttack extends JDialog
{
    private final Creature creature;
    private final AttackModel attToLearn;
    private AttackSlot selectedSlot;
    
    private LearnAttack(Dialog parent, Creature creature, AttackModel attackToLearn)
    {
        super(parent,true);
        initComponents();
        this.creature = Objects.requireNonNull(creature);
        this.attToLearn = Objects.requireNonNull(attackToLearn);
        this.selectedSlot = null;
        init();
    }
    
    private LearnAttack(Frame parent, Creature creature, AttackModel attackToLearn)
    {
        super(parent,true);
        initComponents();
        this.creature = Objects.requireNonNull(creature);
        this.attToLearn = Objects.requireNonNull(attackToLearn);
        this.selectedSlot = null;
        init();
    }
    
    public static final AttackSlot open(Window parent, Creature creature, AttackModel attackToLearn)
    {
        LearnAttack la;
        if(parent == null)
            la = new LearnAttack((Frame) null, creature, attackToLearn);
        else if(parent instanceof Frame)
            la = new LearnAttack((Frame) parent, creature, attackToLearn);
        else if(parent instanceof Dialog)
            la = new LearnAttack((Dialog) parent, creature, attackToLearn);
        else return null;
        la.setVisible(true);
        return la.selectedSlot;
    }
    
    private void init()
    {
        setResizable(false);
        Utils.focus(this);
        
        setTitle("Aprender ataque nuevo");
        
        jTextPane1.setText(creature.getName() + " intena aprender el ataque \"" + attToLearn.getName() +
                "\", pero no puede aprender más de 4 ataques."
                + "Debes elegir un ataque para substituirlo o no aprender el ataque.");
        fillAttacks();
    }
    
    private void fillAttacks()
    {
        var atts = creature.getAttackManager();
        for(var slot : AttackSlot.iterable())
        {
            Attack a = atts.getAttack(slot);
            JButton but = attackButton(slot);
            if(a == null)
            {
                but.setEnabled(false);
                but.setText("----------");
                but.setBackground(Color.WHITE);
                but.setForeground(Color.BLACK);
                forgetButton(slot).setEnabled(false);
                continue;
            }
            but.setEnabled(true);
            but.setText(a.getName() + " (" + a.getCurrentPP() + "/" + a.getMaxPP() + ")");
            but.setBackground(a.getElementalType().getColor());
            but.setForeground(a.getElementalType().getFontColor());
        }
        
        att5.setEnabled(true);
        att5.setText(attToLearn.getName());
        att5.setBackground(attToLearn.getElementalType().getColor());
        att5.setForeground(attToLearn.getElementalType().getFontColor());
    }
    
    private JButton attackButton(AttackSlot slot)
    {
        switch(slot)
        {
            default: throw new IllegalStateException();
            case SLOT_1: return att1;
            case SLOT_2: return att2;
            case SLOT_3: return att3;
            case SLOT_4: return att4;
        }
    }
    
    private JButton forgetButton(AttackSlot slot)
    {
        switch(slot)
        {
            default: throw new IllegalStateException();
            case SLOT_1: return forget1;
            case SLOT_2: return forget2;
            case SLOT_3: return forget3;
            case SLOT_4: return forget4;
        }
    }
    
    private void forget(AttackSlot slot)
    {
        Attack a = creature.getAttack(slot);
        if(!askSure(a))
            return;
        selectedSlot = slot;
        dispose();
    }
    
    private boolean askSure(Attack attack)
    {
        return JOptionPane.showConfirmDialog(this,"¿Estas seguro de que quieres olvidar el ataque \"" + 
                attack.getName() + "\" por \"" + attToLearn.getName() + "\"?",
                "",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        forget1 = new javax.swing.JButton();
        forget2 = new javax.swing.JButton();
        forget3 = new javax.swing.JButton();
        forget4 = new javax.swing.JButton();
        att1 = new javax.swing.JButton();
        att2 = new javax.swing.JButton();
        att3 = new javax.swing.JButton();
        att4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        forget5 = new javax.swing.JButton();
        att5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jTextPane1.setEditable(false);
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ataques Conocidos"));

        forget1.setText("OLVIDAR");
        forget1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forget1ActionPerformed(evt);
            }
        });

        forget2.setText("OLVIDAR");
        forget2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forget2ActionPerformed(evt);
            }
        });

        forget3.setText("OLVIDAR");
        forget3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forget3ActionPerformed(evt);
            }
        });

        forget4.setText("OLVIDAR");
        forget4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forget4ActionPerformed(evt);
            }
        });

        att1.setText("jButton6");
        att1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                att1ActionPerformed(evt);
            }
        });

        att2.setText("jButton7");
        att2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                att2ActionPerformed(evt);
            }
        });

        att3.setText("jButton8");
        att3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                att3ActionPerformed(evt);
            }
        });

        att4.setText("jButton9");
        att4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                att4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(att1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forget1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(att2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forget2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(att4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(att3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forget3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(forget4, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forget1)
                    .addComponent(att1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forget2)
                    .addComponent(att2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forget3)
                    .addComponent(att3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forget4)
                    .addComponent(att4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ataque a aprender"));

        forget5.setText("NO APRENDER");
        forget5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forget5ActionPerformed(evt);
            }
        });

        att5.setText("jButton10");
        att5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                att5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(att5, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forget5)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forget5)
                    .addComponent(att5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void att1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_att1ActionPerformed
        AttackViewer.open(this, creature.getAttack(AttackSlot.SLOT_1));
    }//GEN-LAST:event_att1ActionPerformed

    private void att2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_att2ActionPerformed
        AttackViewer.open(this,creature.getAttack(AttackSlot.SLOT_2));
    }//GEN-LAST:event_att2ActionPerformed

    private void att3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_att3ActionPerformed
        AttackViewer.open(this,creature.getAttack(AttackSlot.SLOT_3));
    }//GEN-LAST:event_att3ActionPerformed

    private void att4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_att4ActionPerformed
        AttackViewer.open(this,creature.getAttack(AttackSlot.SLOT_4));
    }//GEN-LAST:event_att4ActionPerformed

    private void att5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_att5ActionPerformed
        AttackViewer.open(this, AttackPool.createAttack(attToLearn));
    }//GEN-LAST:event_att5ActionPerformed

    private void forget1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forget1ActionPerformed
        forget(AttackSlot.SLOT_1);
    }//GEN-LAST:event_forget1ActionPerformed

    private void forget2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forget2ActionPerformed
        forget(AttackSlot.SLOT_2);
    }//GEN-LAST:event_forget2ActionPerformed

    private void forget3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forget3ActionPerformed
        forget(AttackSlot.SLOT_3);
    }//GEN-LAST:event_forget3ActionPerformed

    private void forget4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forget4ActionPerformed
        forget(AttackSlot.SLOT_4);
    }//GEN-LAST:event_forget4ActionPerformed

    private void forget5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forget5ActionPerformed
        if(JOptionPane.showConfirmDialog(this,
                "¿Seguro que no quieres aprender el ataque \"" + attToLearn.getName() +
                        "\"?","", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION)
            return;
        selectedSlot = null;
        dispose();
    }//GEN-LAST:event_forget5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton att1;
    private javax.swing.JButton att2;
    private javax.swing.JButton att3;
    private javax.swing.JButton att4;
    private javax.swing.JButton att5;
    private javax.swing.JButton forget1;
    private javax.swing.JButton forget2;
    private javax.swing.JButton forget3;
    private javax.swing.JButton forget4;
    private javax.swing.JButton forget5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
