/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kp.cbs.battle;

import java.util.Objects;
import javax.swing.JDialog;
import kp.cbs.creature.feat.StatId;
import kp.cbs.creature.feat.StatsComparison;
import kp.cbs.utils.Utils;

/**
 *
 * @author mpasc
 */
public class LevelUpStatComparison extends JDialog
{
    private final StatsComparison stats;
    private boolean pressed;
    
    private LevelUpStatComparison(Battle parent, StatsComparison comparison)
    {
        super(parent,true);
        initComponents();
        this.stats = Objects.requireNonNull(comparison);
        pressed = false;
        init();
    }
    
    private void init()
    {
        setResizable(false);
        Utils.focus(this);
        showStats(true);
    }
    
    private void showStats(boolean addition)
    {
        String prefix = addition ? "+" : "";
        
        ps.setText(prefix + stats.getStatValue(StatId.HEALTH_POINTS, addition));
        attack.setText(prefix + stats.getStatValue(StatId.ATTACK, addition));
        defense.setText(prefix + stats.getStatValue(StatId.DEFENSE, addition));
        attackSp.setText(prefix + stats.getStatValue(StatId.SPECIAL_ATTACK, addition));
        defenseSp.setText(prefix + stats.getStatValue(StatId.SPECIAL_DEFENSE, addition));
        speed.setText(prefix + stats.getStatValue(StatId.SPEED, addition));
    }
    
    public static final void open(Battle parent, StatsComparison comparison)
    {
        LevelUpStatComparison lusc = new LevelUpStatComparison(parent, comparison);
        lusc.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        butt = new javax.swing.JButton();
        ps = new javax.swing.JLabel();
        attack = new javax.swing.JLabel();
        defense = new javax.swing.JLabel();
        attackSp = new javax.swing.JLabel();
        defenseSp = new javax.swing.JLabel();
        speed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("PS:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Ataque:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Defensa");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Ataque Especial:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Defensa Especial:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Velocidad:");

        butt.setText("Continuar");
        butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttActionPerformed(evt);
            }
        });

        ps.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ps.setText("+9999");

        attack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        attack.setText("+9999");

        defense.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        defense.setText("+9999");

        attackSp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        attackSp.setText("+9999");

        defenseSp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        defenseSp.setText("+9999");

        speed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        speed.setText("+9999");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(speed))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ps))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(attack))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(defense))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(attackSp))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(defenseSp)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ps))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(attack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(defense))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(attackSp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(defenseSp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(speed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butt, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttActionPerformed
        if(!pressed)
        {
            pressed = true;
            showStats(false);
            return;
        }
        dispose();
    }//GEN-LAST:event_buttActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attack;
    private javax.swing.JLabel attackSp;
    private javax.swing.JButton butt;
    private javax.swing.JLabel defense;
    private javax.swing.JLabel defenseSp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel ps;
    private javax.swing.JLabel speed;
    // End of variables declaration//GEN-END:variables
}
