/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kp.cbs.editor.utils;

import java.util.Objects;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import kp.cbs.creature.feat.StatId;
import kp.cbs.creature.race.Evolution.EvolutionConditionType;
import kp.cbs.creature.race.Evolution.EvolveCondition;
import kp.cbs.creature.race.Evolution.StatEvolveCondition;
import kp.cbs.editor.RaceEditor;
import kp.cbs.utils.Utils;

/**
 *
 * @author Asus
 */
public class EvolveStatSelection extends JDialog
{
    private final StatEvolveCondition cond;
    
    private EvolveStatSelection(RaceEditor parent, StatEvolveCondition cond)
    {
        super(parent, true);
        this.cond = Objects.requireNonNull(cond);
        initComponents();
        init();
    }
    
    private void init()
    {
        setResizable(false);
        Utils.focus(this);
        
        this.stat0.setModel(new DefaultComboBoxModel<>(StatId.values()));
        this.stat1.setModel(new DefaultComboBoxModel<>(StatId.values()));
        
        this.cmpText.setText(cond.getType() == EvolutionConditionType.STAT_GREATER_THAN ? "Mayor que" : "Igual a");
        this.stat0.setSelectedItem(cond.getFirstStat());
        this.stat1.setSelectedItem(cond.getSecondStat());
    }
    
    public static final void open(RaceEditor parent, EvolveCondition cond)
    {
        if(cond instanceof StatEvolveCondition)
        {
            var sel = new EvolveStatSelection(parent, (StatEvolveCondition) cond);
            sel.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        stat0 = new javax.swing.JComboBox<>();
        cmpText = new javax.swing.JLabel();
        stat1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("¿Que dos Stats quieres comparar?");

        cmpText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cmpText.setText("jLabel2");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addComponent(stat1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stat0, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmpText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stat0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmpText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cond.setFirstStat((StatId) stat0.getSelectedItem());
        cond.setSecondStat((StatId) stat1.getSelectedItem());
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cmpText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<StatId> stat0;
    private javax.swing.JComboBox<StatId> stat1;
    // End of variables declaration//GEN-END:variables
}
